name: flutter_chat_grpc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  grpc: ^1.0.1
  protobuf: ^1.0.1
  meta: ^1.1.8
  shimmer: ^1.1.0
  rxdart: ^0.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
